export const HOSTELS = [
  {
    id: 0,
    name: "Anandacoomaraswamy Female Hostel",

    subWarden: "	Ms.R.Subani",
    address: "Ramanathan Road, Thirunelvely,",
    tel: "021 222 2306",
    location: "//Map location",
  },
  {
    id: 1,
    name: "Balasingam Hall Male Hostel",
    subWarden: "Mr.P.Poologanathan",
    address: "	Ramanathan Road, Thirunelvely,",
    tel: "	021 222 2304",
    location: "//Map location",
  },
  {
    id: 2,
    name: "Kaithady Female Hostel",
    subWarden: "Ms.M.Lalithamani",
    address: "	Kaithady",
    tel: "	021 205 7144",
    location: "//Map location",
  },
  {
    id: 3,
    name: "Kaithady Male Hostel",
    subWarden: "	Mr.P.Sasitharan",
    address: "	Kaithady",
    tel: "	021 205 7145",
    location: "//Map location",
  },
  {
    id: 4,
    name: "Kondavil Female Hostel",
    subWarden: "Mrs.S.Vigetha",
    address: "	Palaly Road, Kondavil",
    tel: "	021 221 4549",
    location: "//Map location",
  },
  {
    id: 5,
    name: "Kondavil Male Hostel",
    subWarden: "Mr.S.Sarangan",
    address: "Palaly Road, Kondavil",
    tel: "	021 221 4557",
    location: "//Map location",
  },
  {
    id: 6,
    name: "Medical Female Hostel",
    subWarden: "Mrs. G. Jatheesan,",
    address: "	In front of Jaffna Teaching Hospital",
    tel: "021 222 5369",
    location: "//Map location",
  },
  {
    id: 7,
    name: "Medical Male Hostel",
    subWarden: "Mr. V. Kugatharsan",
    address: "In front of Jaffna Teaching Hospital",
    tel: "	021 221 7720",
    location: "//Map location",
  },
  {
    id: 8,
    name: "New Female Hostel – I",
    subWarden: "	Mrs.T.Lavanya",
    address: "	Campus Lane, Thirnelvely",
    tel: "021 221 5890",
    location: "//Map location",
  },
  {
    id: 9,
    name: "New Female Hostel – II",
    subWarden: "	Mrs.P.Gasthoory",
    address: "Campus Lane, Thirnelvely",
    contactNo: "	021 221 5891",
    location: "//Map location",
  },
  {
    id: 10,
    name: "RAFA Female Hostel",
    subWarden: "	Mrs.V.Paskaralingam",
    address: "Maruthanarmadam, Jaffna",
    contactNo: "	021 224 2581",
    location: "//Map location",
  },
  {
    id: 11,
    name: "Male Hostel – I",
    subWarden: "	Mr.K.Kabilan",
    address: "Kilinochchi Premises",
    contactNo: "	021 206 0177",
    location: "//Map location",
  },
  {
    id: 12,
    name: "Male Hostel – II",
    subWarden: "	Mr.K.Kabilan",
    address: "Kilinochchi Premises",
    tel: "	021 206 0177",
    location: "//Map location",
  },
  {
    id: 13,
    name: "Male Hostel – III",
    subWarden: "	Mr.K.Kabilan",
    address: "Kilinochchi Premises",
    contactNo: "	021 206 0177",
    location: "//Map location",
  },
  {
    id: 14,
    name: "Female Hostel – I",
    warden: "	Ms.S.Jeyavathani",
    subWarden: "",
    address: "Kilinochchi Premises",
    contactNo: "	021 206 0181",
    location: "//Map location",
  },
  {
    id: 15,
    name: "Female Hostel – II",
    warden: "	Ms.S.Jeyavathani",
    subWarden: "",
    address: "Kilinochchi Premises",
    contactNo: "	021 206 0181",
    location: "Map location",
  },
  {
    id: 16,
    name: "Female Hostel – III",
    subWarden: "Ms.A.Pathmapriya",
    address: "Kilinochchi Premises",
    contactNo: "	021 206 0181",
    location: "//Map location",
  },
];
