export const staffs = [
  {
    id: 0,
    name: "Mr .Kethiswaran",
    image: "/assets/images/staffimg.png",
    designation: "Senior Assistant Registrar",
    abbr: "SAR",
    featured: false,
    description: "//description",
  },
  {
    id: 1,
    name: "Mr .Satkunam",
    image: "/assets/images/staffimg.png",
    designation: "Assistant Secretary",
    abbr: "AS",
    featured: false,
    description: "//description",
  },
  {
    id: 2,
    name: "Mr .Sasikaran",
    image: "/assets/images/staffimg.png",
    designation: " Assistant Accountant",
    abbr: "AA",
    featured: false,
    description: "//description",
  },
  {
    id: 3,
    name: "Mr .Ganesher",
    image: "/assets/images/staffimg.png",
    designation: "Assistant Registrar",
    abbr: "AR",
    featured: true,
    description: "//description",
  },
];
