export const districts = [
  {
    district: "Ampara",
    division: [
      "Addalachchenai",
      "Akkaraipattu",
      "Alayadiwembu",
      "Ampara",
      "Damana",
      "Dehiattakandiya",
      "Eragama (Irakkamam)",
      "Kalmunai (incl. Tamil Division with 29,800 pop. in 2012)",
      "Karativu",
      "Lahugala",
      "Mahaoya",
      "Navithanveli",
      "Ninthavur",
      "Padiyathalawa",
      "Pothuvil",
      "Sainthamarathu",
      "Sammanthurai",
      "Thirukkovil",
      "Uhana",
    ],
  },

  {
    district: "Anuradhapura",
    division: [
      "Galenbindunuwewa",
      "Galnewa",
      "Horowpothana",
      "Ipalogama",
      "Kahatagasdigiliya",
      "Kebithigollewa",
      "Kekirawa",
      "Mahavilachchiya",
      "Medawachchiya",
      "Mihinthale",
      "Nachchadoowa",
      "Nochchiyagama",
      "Nuwaragam Palatha Central",
      "Nuwaragam Palatha East",
      "Padaviya",
      "Palagala",
      "Palugaswewa",
      "Rajanganaya",
      "Rambewa",
      "Thalawa",
      "Thambuttegama",
      "Thirappane",
    ],
  },
  {
    district: "Badulla",
    division: [
      "Badulla",
      "Bandarawela",
      "Ella",
      "Haldummulla",
      "Hali-Ela",
      "Haputale",
      "Kandaketiya",
      "Lunugala",
      "Mahiyanganaya",
      "Meegahakivula",
      "Passara",
      "Rideemaliyadda",
      "Soranathota",
      "Uva-Paranagama",
      "Welimada",
    ],
  },
  {
    district: "Batticaloa",
    division: [
      "Eravur Pattu",
      "Eravur Town",
      "Kattankudy",
      "Koralai Pattu (Valachenai)",
      "Koralai Pattu Central",
      "Koralai Pattu North (Vaharai)",
      "Koralai Pattu South (Kiran)",
      "Koralai Pattu West (Oddamavadi)",
      "Manmunai North",
      "Manmunai Pattu (Araipattai)",
      "Manmunai South & Eruvil Pattu",
      "Manmunai South West",
      "Manmunai West",
      "Porativu Pattu",
    ],
  },
  {
    district: "Colombo",
    division: [
      "Colombo",
      "Dehiwala",
      "Homagama",
      "Kaduwela",
      "Kesbewa",
      "Kolonnawa",
      "Maharagama",
      "Moratuwa",
      "Padukka",
      "Ratmalana",
      "Seethawaka (Hanwella)",
      "Sri Jayawardanapura Kotte",
      "Thimbirigasyaya",
    ],
  },
  {
    district: "Galle",
    division: [
      "Akmeemana",
      "Ambalangoda",
      "Baddegama",
      "Balapitiya",
      "Benthota",
      "Bope-Poddala",
      "Elpitiya",
      "Galle Four Gravets (Kadawath Sathra)",
      "Gonapinuwala",
      "Habaraduwa",
      "Hikkaduwa",
      "Imaduwa",
      "Karandeniya",
      "Nagoda",
      "Neluwa",
      "Niyagama",
      "Thawalama",
      "Welivitiya-Divithura",
      "Yakkalamulla",
    ],
  },
  {
    district: "Gampaha",
    division: [
      "Attanagalla",
      "Biyagama",
      "Divulapitiya",
      "Dompe",
      "Gampaha",
      "Ja-Ela",
      "Katana",
      "Kelaniya",
      "Mahara",
      "Minuwangoda",
      "Mirigama",
      "Negombo",
      "Wattala",
    ],
  },
  {
    district: "Hambantota",
    division: [
      "Ambalantota",
      "Angunakolapelessa",
      "Beliatta",
      "Hambantota",
      "Katuwana",
      "Lunugamvehera",
      "Okewela",
      "Sooriyawewa",
      "Tangalle",
      "Thissamaharama",
      "Walasmulla",
      "Weeraketiya",
    ],
  },
  {
    district: "Jaffna",
    division: [
      "Delft",
      "Island North (Kayts)",
      "Island South (Velanai)",
      "Jaffna",
      "Karainagar",
      "Nallur",
      "Thenmaradchi (Chavakachcheri)",
      "Vadamaradchi East (Maruthnkerny)",
      "Vadamaradchi North (Point Pedro)",
      "Vadamaradchi South-West (Karaveddy)",
      "Valikamam East (Kopay)",
      "Valikamam North (Tellippalai)",
      "Valikamam South (Uduvil)",
      "Valikamam South-West (Sandilipay)",
      "Valikamam West (Chankanai)",
    ],
  },
  {
    district: "Kalutara",
    division: [
      "Agalawatta",
      "Bandaragama",
      "Beruwala",
      "Bulathsinhala",
      "Dodangoda",
      "Horana",
      "Ingiriya",
      "Kalutara",
      "Madurawela",
      "Mathugama",
      "Millaniya",
      "Palindanuwara",
      "Panadura",
      "Walallavita",
    ],
  },
  {
    district: "Kandy",
    division: [
      "Akurana",
      "Delthota",
      "Doluwa",
      "Ganga Ihala Korale",
      "Harispattuwa",
      "Hatharaliyadda",
      "Kandy Four Gravets & Gangawata Korale",
      "Kundasale",
      "Medadumbara",
      "Minipe",
      "Panvila",
      "Pasbage Korale",
      "Pathadumbara",
      "Pathahewaheta",
      "Poojapitiya",
      "Thumpane",
      "Udadumbara",
      "Udapalatha",
      "Udunuwara",
      "Yatinuwara",
    ],
  },

  {
    district: "Kegalle",
    division: [
      "Aranayaka",
      "Bulathkohupitiya",
      "Dehiovita",
      "Deraniyagala",
      "Galigamuwa",
      "Kegalle",
      "Mawanella",
      "Rambukkana",
      "Ruwanwella",
      "Warakapola",
      "Yatiyanthota",
    ],
  },

  {
    district: "Kilinochchi",
    division: ["Kandavalai", "Karachchi", "Pachchilaipalli", "Poonakary"],
  },

  {
    district: "Kurunegala",
    division: [
      "Alawwa",
      "Ambanpola",
      "Bamunakotuwa",
      "Bingiriya",
      "Ehetuwewa",
      "Galgamuwa",
      "Ganewatta",
      "Giribawa",
      "Ibbagamuwa",
      "Kobeigane",
      "Kotavehera",
      "Kuliyapitiya East",
      "Kuliyapitiya West",
      "Kurunegala",
      "Mahawa",
      "Mallawapitiya",
      "Maspotha",
      "Mawathagama",
      "Narammala",
      "Nikaweratiya",
      "Panduwasnuwara East (Katupotha)",
      "Panduwasnuwara West",
      "Pannala",
      "Polgahawela",
      "Polpithigama",
      "Rasnayakapura",
      "Rideegama",
      "Udubaddawa",
      "Wariyapola",
      "Weerambugedara",
    ],
  },

  {
    district: "Mannar",
    division: ["Madhu", "Mannar Town", "Manthai West", "Musalai", "Nanaddan"],
  },

  {
    district: "Matale",
    division: [
      "Ambanganga Korale",
      "Dambulla",
      "Galewela",
      "Laggala-Pallegama",
      "Matale",
      "Naula",
      "Pallepola",
      "Rattota",
      "Ukuwela",
      "Wilgamuwa",
      "Yatawatta",
    ],
  },

  {
    district: "Matara",
    division: [
      "Akuressa",
      "Athuraliya",
      "Devinuwara",
      "Dickwella",
      "Hakmana",
      "Kamburupitiya",
      "Kirinda Puhulwella",
      "Kotapola",
      "Malimbada",
      "Matara Four Gravets",
      "Mulatiyana",
      "Pasgoda",
      "Pitabeddara",
      "Thihagoda",
      "Weligama",
      "Welipitiya",
    ],
  },

  {
    district: "Moneragala",
    division: [
      "Badalkumbura",
      "Bibile",
      "Buttala",
      "Katharagama",
      "Madulla",
      "Medagama",
      "Moneragala",
      "Sevanagala",
      "Siyambalanduwa",
      "Thanamalvila",
      "Wellawaya",
    ],
  },

  {
    district: "Mullaitivu",
    division: [
      "Manthai East (Pandiyankulam)",
      "Maritimepattu",
      "Oddusuddan",
      "Puthukudiyiruppu",
      "Thunukkai",
      "Welioya",
    ],
  },

  {
    district: "Nuwara Eliya",
    division: [
      "Ambagamuwa",
      "Hanguranketha",
      "Kothmale",
      "Nuwara Eliya",
      "Walapane",
    ],
  },

  {
    district: "Polonnaruwa",
    division: [
      "Dimbulagala",
      "Elahera",
      "Hingurakgoda",
      "Lankapura",
      "Medirigiriya",
      "Thamankaduwa",
      "Welikanda",
    ],
  },

  {
    district: "Puttalam",
    division: [
      "Anamaduwa",
      "Arachchikattuwa",
      "Chilaw",
      "Dankotuwa",
      "Kalpitiya",
      "Karuwalagaswewa",
      "Madampe",
      "Mahakumbukkadawala",
      "Mahawewa",
      "Mundalama",
      "Nattandiya",
      "Nawagattegama",
      "Pallama",
      "Puttalam",
      "Vanathavilluwa",
      "Wennappuwa",
    ],
  },

  {
    district: "Ratnapura",
    division: [
      "Ayagama",
      "Balangoda",
      "Eheliyagoda",
      "Elapattha",
      "Embilipitiya",
      "Godakawela",
      "Imbulpe",
      "Kahawatta",
      "Kalawana",
      "Kiriella",
      "Kolonna",
      "Kuruvita",
      "Nivithigala",
      "Opanayaka",
      "Pelmadulla",
      "Ratnapura",
      "Weligepola",
    ],
  },

  {
    district: "Trincomalee",
    division: [
      "Gomarankadawala",
      "Kantalai",
      "Kinniya",
      "Kuchchaveli",
      "Morawewa",
      "Muttur",
      "Padavi Sri Pura",
      "Seruvila",
      "Thambalagamuwa",
      "Trincomalee Town and Gravets",
      "Verugal (Echchilampattai)",
    ],
  },

  {
    district: "Vavuniya",
    division: [
      "Vavuniya",
      "Vavuniya North",
      "Vavuniya South",
      "Vengalacheddikulam",
    ],
  },
];

export const faculties = [
  "Agriculture",
  "Allied Health Sciences",
  "Arts",
  "Engineering",
  "Graduate Studies",
  "Hindu Studies",
  "Management Studies & Commerce",
  "Medicine",
  "Science",
  "Technology",
];

// export const faculties = [
//   {
//     faculty: "Agriculture",
//     courses: [

//     ],
//    },
//   { faculty: "Allied Health Sciences",
//     courses: [

//     ] ,
//   },
//   { faculty: "Arts",
//   courses: [

//   ],
//  },

//   { faculty: "Engineering", courses: [] },
//   { faculty: "Graduate Studies", courses: [] },
//   { faculty: "Hindu Studies", courses: [] },
//   { faculty: "Management Studies & Commerce", courses: [] },
//   { faculty: "Medicine", courses: [] },
//   {
//     faculty: "Science",
//      courses: [
//         "Botany",
//         "Chemistry",
//         "Computer Science",
//         "Fisheries Science",
//         "Mathematics & Statistics",
//         "Physics",
//         "Zoology"
//       ] ,
//     },
//   { faculty: "Technology", courses: [] },
// ];

export const hostels = [
  "Anandacoomaraswamy Female Hostel",
  "Balasingam Hall Male Hostel",
  "Kaithady Female Hostel	",
  "Kaithady Male Hostel	",
  "Kondavil Female Hostel	",
  "Kondavil Male Hostel",
  "Medical Female Hostel	",
  "Medical Male Hostel	",
  "New Female Hostel – I	",
  "New Female Hostel – II	",
  "RAFA Female Hostel",
  "Male Hostel – I",
  "Male Hostel– II",
  "Male Hostel – III",
  "Female Hostel – I	",
  "Female Hostel– II",
  "Female Hostel – III	",
];
